<?php

declare(strict_types=1);

namespace LMWF\ErrorHandling;

enum ExceptionCode: int
{
    case APP_TRAVERSABLE_UNEXPECTED_PROPERTY_TYPE = 8010100;
    case CONF_ROUTEDEFPARSER_BASE_URL_MUST_NOT_HAVE_TRAILING_SLASH = 9000100;
    case CONF_ROUTEDEFPARSER_PAGEPARAM_CONF_WRONG_TYPE = 9000101;
    case HTTP_DATASTRUCTURES_ROUTEDEF_N_ARGS_LOWER_IS_NEG = 7030103;
    case HTTP_DATASTRUCTURES_ROUTEDEF_N_ARGS_UPPER_IS_BELOW_LOWER_IS_NEG = 7030104;
    case HTTP_DATASTRUCTURES_ROUTEDEF_PAGE_CONF_FIRST_VALUE_CANNOT_INHERIT = 7030111;
    case HTTP_DATASTRUCTURES_ROUTEDEF_PAGE_CONF_KEY_NOT_INT = 7030108;
    case HTTP_DATASTRUCTURES_ROUTEDEF_PAGE_CONF_KEY_OUT_OF_BOUNDS = 7030102;
    case HTTP_DATASTRUCTURES_ROUTEDEF_PAGE_CONF_MISSING = 7030109;
    case HTTP_DATASTRUCTURES_ROUTEDEF_PAGE_CONF_VALUE_INVALID_TYPE = 7030110;
    case HTTP_DATASTRUCTURES_ROUTEDEF_PAGEPARAM_IS_NOT_NULL = 7030100;
    case HTTP_DATASTRUCTURES_ROUTEDEF_PAGEPARAM_IS_NULL = 7030101;
    case HTTP_DATASTRUCTURES_ROUTEDEF_ROLE_IS_NOT_A_STRING = 7030105;
    case HTTP_DATASTRUCTURES_ROUTEDEF_SUBROUTE_DEF_IS_NOT_A_ROUTEDEF = 7030107;
    case HTTP_DATASTRUCTURES_ROUTEDEF_SUBROUTE_PATH_SEGMENT_IS_NOT_A_STRING = 7030106;
    case HTTP_FACTORY_PAGEFACTORY_ENT_PAGE_METADATA_CONF_WITH_0_PARAM = 7020101;
    case HTTP_ROUTING_ROUTE_PARAM_IS_NOT_STRING = 7010104;
    case HTTP_ROUTING_ROUTE_ROOT_ROUTE_ACCEPTS_PARAMS = 7010103;
    case HTTP_ROUTING_ROUTE_ROOT_ROUTE_HAS_CHILD_WITH_EMPTY_SEG = 7010102;
    case HTTP_ROUTING_ROUTE_ROOT_ROUTE_HAS_NON_EMPTY_SEG = 7010101;
    case HTTP_ROUTING_ROUTE_ROOT_ROUTE_WITH_DFT_CONTROLLER = 7010100;
    case HTTP_ROUTING_ROUTER_GIVEN_PATH_IS_NOT_ABSOLUTE = 7010200;
}
