<?php

declare(strict_types=1);

namespace LMWF\ErrorHandling;

enum ExceptionCode: int
{
    case APP_TRAVERSABLE_UNEXPECTED_PROPERTY_TYPE = 8010100;
    case CONF_HTTP_ROUTEDEF_N_ARGS_LOWER_IS_NEG = 9010103;
    case CONF_HTTP_ROUTEDEF_N_ARGS_UPPER_IS_BELOW_LOWER_IS_NEG = 9010104;
    case CONF_HTTP_ROUTEDEF_PAGEPARAM_IS_NOT_NULL = 9010100;
    case CONF_HTTP_ROUTEDEF_PAGEPARAM_IS_NULL = 9010101;
    case CONF_HTTP_ROUTEDEF_ROLE_IS_NOT_A_STRING = 9010105;
    case CONF_HTTP_ROUTEDEF_SUBROUTE_DEF_IS_NOT_A_ROUTEDEF = 9010107;
    case CONF_HTTP_ROUTEDEF_SUBROUTE_PATH_SEGMENT_IS_NOT_A_STRING = 9010106;
    case CONF_ROUTEDEFPARSER_BASE_URL_MUST_NOT_HAVE_TRAILING_SLASH = 9000100;
    case CONF_ROUTEDEFPARSER_PAGEPARAM_CONF_WRONG_TYPE = 9000101;
    case HTTP_ROUTING_ROUTE_ROOT_ROUTE_ACCEPTS_PARAMS = 7010103;
    case HTTP_ROUTING_ROUTE_ROOT_ROUTE_HAS_CHILD_WITH_EMPTY_SEG = 7010102;
    case HTTP_ROUTING_ROUTE_ROOT_ROUTE_HAS_NON_EMPTY_SEG = 7010101;
    case HTTP_ROUTING_ROUTE_ROOT_ROUTE_WITH_DFT_CONTROLLER = 7010100;
}
